name: 🔗 GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  android-build:
    name: 🤖 Android
    uses: ./.github/workflows/android_builds.yml

  #windows-build:
  #  name: 🏁 Windows
  #  uses: ./.github/workflows/windows_builds.yml
