name: 🔗 GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ios-build:
    name: 🍏 iOS
    if: needs.static-checks.outputs.sources-changed == 'true' || github.event_name != 'pull_request'
    uses: ./.github/workflows/ios_builds.yml

  macos-build:
    name: 🍎 macOS
    if: needs.static-checks.outputs.sources-changed == 'true' || github.event_name != 'pull_request'
    uses: ./.github/workflows/macos_builds.yml
