name: 🏁 Windows Builds
on:
  workflow_call:
  workflow_dispatch:

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
    debug_symbols=no
  SCONS_CACHE_MSVC_CONFIG: true
  PYTHONIOENCODING: utf8

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: windows-latest
    name: ${{ matrix.name }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            cache-name: windows-editor
            target: editor
            scons-flags: >-
              windows_subsystem=console
              vsproj=yes
              vsproj_gen_only=no
            bin: ./bin/godot.windows.editor.x86_64.exe
            compiler: msvc

          - name: Editor w/ clang-cl (target=editor, use_llvm=yes)
            cache-name: windows-editor-clang
            target: editor
            scons-flags: >-
              windows_subsystem=console
              use_llvm=yes
            bin: ./bin/godot.windows.editor.x86_64.llvm.exe
            compiler: clang

          - name: Template (target=template_release)
            cache-name: windows-template
            target: template_release
            bin: ./bin/godot.windows.template_release.x86_64.console.exe
            compiler: msvc

          - name: Template w/ GCC (target=template_release, use_mingw=yes)
            cache-name: windows-template-gcc
            # MinGW takes MUCH longer to compile; save time by only targeting Template.
            target: template_release
            scons-flags: use_mingw=yes
            bin: ./bin/godot.windows.template_release.x86_64.console.exe
            compiler: gcc

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Test
        shell: sh
        run: |
          ls
          cd .scons_cache
          ls

      - name: Upload cache
        if: matrix.compiler == 'msvc'
        uses: ./.github/actions/upload-artifact
        with:
          name: cache
          path: ${{ github.workspace }}/.scons_cache/
